version: "3.8"

services:
  auth-db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "local-dev"
    volumes:
      - ./dev-db/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    container_name: auth-db
